### ISSUE TITLE
Add button does not work

### ISSUE THREAD

**Issue by IkariAtari** [post-kerbin-mining-corporation/Waterfall#101]
Pressing the Add button in the effects panel does not seem to add any effects.
I tried it with version 7.1 and 7.0.

**Comment by ChrisAdderley** [comment]
Definitely does for me, going to need more info....

**Comment by IsaQuest** [comment]
Make sure you add the effect parent. this is the transform in the model that has the thrust on it. You can find it in the Engine's CFG file under ModuleEngines/ModuleEnginesFX. It is usually something like thrustTransform.
