### ISSUE TITLE
Plumes don't scale with TweakScale

### ISSUE THREAD

**Issue by josuenos** [post-kerbin-mining-corporation/Waterfall#116]
When engines are scaled up/down using TweakScale, the Waterfall plume does not scale accordingly.

**Comment by ChrisAdderley** [comment]
This is a tweakscale problem, not a Waterfall problem.

**Comment by JonnyOThan** [comment]
FWIW, this works with TweakScale Rescaled: https://github.com/JonnyOThan/TweakScale
