### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by AAAkakei** [post-kerbin-mining-corporation/Waterfall#128]
@ChrisAdderley Hello author, I would like to ask if this mod does not have custom localization support, because I am using this mod to show English, not very smooth, I want to add my own language text, but I have tried, localization is not successful, so I come to ask you

If you have time, please help me, thank you 
![QQ截图20231103004827](https://github.com/post-kerbin-mining-corporation/Waterfall/assets/115620798/80117a39-2147-4c22-813e-91989ec67857)
![QQ截图20231103004901](https://github.com/post-kerbin-mining-corporation/Waterfall/assets/115620798/971649ef-b7df-4e65-a68a-e3deb6523a97)
![QQ截图20231103004939](https://github.com/post-kerbin-mining-corporation/Waterfall/assets/115620798/ac8774dd-f717-4b50-b0c5-d803c5300ddf)

**Comment by ChrisAdderley** [comment]
Hey, localizing the effects window is a bit too much effort for me right now, there are so many strings.
