### ISSUE TITLE
Scrollwheel fix broke something after revert to launch

### ISSUE THREAD

**Issue by JonnyOThan** [post-kerbin-mining-corporation/Waterfall#150]
Not quite sure what's going on here, but after a revert to launch you can't click a lot of stuff on the craft.  If you open the editor UI you can see that it's covering the area where you can't click.  It also says "couldn't find any effects on this craft."

**Comment by JonnyOThan** [comment]
Huh, this actually is two separate issues.  The scrollwheel issue is just that the UI target doesn't get disabled when the window is hidden.  But something is still breaking on revert to launch

**Comment by ChrisAdderley** [comment]
Fixed in dev
