### ISSUE TITLE
Waterfall in-game editor missing after upgrade to 0.10.3

### ISSUE THREAD

**Issue by Armo00** [post-kerbin-mining-corporation/Waterfall#180]
After I upgrade waterfall core to 0.10.3, I noticed that the waterfall in-game editor icon is no longer present in the tool bar. Downgrade to 0.9.0 bring the icon back and the editor works fine. 
Here is the log.
[KSP.log](https://github.com/user-attachments/files/17560229/KSP.log)

**Comment by Rodg88** [comment]
Set the first option in Waterfall/WaterfallSettings.cfg to true to show the editor. It's hidden for normal play now

**Comment by ChrisAdderley** [comment]
Yep, not a bug:
https://github.com/post-kerbin-mining-corporation/Waterfall/wiki/Ingame-Editor-Introduction#activating-the-editor
