### ISSUE TITLE
Possible issue in Settings.cs 

### ISSUE THREAD

**Issue by adam-andrus-ama** [post-kerbin-mining-corporation/Waterfall#31]
I am seeing errors in the ksp log from waterfall.

[LOG 15:41:53.174] [Waterfall][Settings]: Started loading
[ERR 15:41:53.174] Cannot find config in file : WATERFALL_SETTINGS

[LOG 15:41:53.174] [Waterfall][Settings]: Using specified settings

I am not 100% certain but I think the issue is being caused by the way the settings files is calling the config.

settingsNode = GameDatabase.Instance.GetConfigNode("Waterfall/WATERFALL_SETTINGS");

this appears to be different than how the assets are getting called

foreach (ConfigNode node in GameDatabase.Instance.GetConfigNodes("WATERFALL_MODEL"))

I am wondering if the error is being caused by the "Waterfall/" when looking for the config. 

I should clarify that I am running ksp 1.9.1 and can provide a full log if needed.

**Comment by ChrisAdderley** [comment]
Nah those two functions have different signatures. First requires a GameData relative URL, the second just requires the type. 

The error message is a red herring, I haven't really bothered to fix it because the settings are loaded correctly anyways.

**Comment by adam-andrus-ama** [comment]
Cool, good to know :) appreciate all the great work you put into these mods!

**Comment by al2me6** [comment]
I believe this has been fixed by https://github.com/post-kerbin-mining-corporation/Waterfall/pull/104.

**Comment by DRVeyl** [comment]
104 did fix it.  Had to do with accessing something before the database was actually built IIRC.
