### ISSUE TITLE
ADD modifier doesn't reset value

### ISSUE THREAD

**Issue by KnightofStJohn** [post-kerbin-mining-corporation/Waterfall#35]
Hi.
I've noticed that when I try to use the ADD modifier in the editor, for instance to add a random oscillation on the width of a plume, the result is that the plume starts widening indefinitely. I think this is not(?) intended. What should happen is the random value gets added to the standard width (for instance the x and y scale of the tail) and the next tick, the standard width is reset, and a new random value is added. Instead what I think happens is: In the new tick, the width doesn't get reset, and another random value gets added, making the width expand over time.

**Comment by ChrisAdderley** [comment]
Neither does subtract. Unfortunately this isn't actually solveable in the current implementation as it needs a re-write of the integrator.

**Comment by KnightofStJohn** [comment]
oh I see. Well, there are workarounds to accomplish most of what you would use the add and substract modifiers for. so this isn't urgent i guess.

**Comment by ChrisAdderley** [comment]
This should be sorted in 0.5.0, but I'll leave this open until someone other than me has tested it (limited work so far)
