### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by Battleseekuh** [post-kerbin-mining-corporation/Waterfall#36]
how to use i see no symbole at the side or anithing (in the game) pls help.

**Comment by ValiZockt** [comment]
Navigate to your Waterfall folder and open WaterfallSettings.cfg. You have to enable the editor first. 
(https://github.com/post-kerbin-mining-corporation/Waterfall/blob/master/GameData/Waterfall/WaterfallSettings.cfg#L4)

Be also sure to read the wiki, there's a how to get started guide: https://github.com/post-kerbin-mining-corporation/Waterfall/wiki/ModuleWaterfallFX
