### ISSUE TITLE
Ability to hide the toolbar button

### ISSUE THREAD

**Issue by tyrope** [post-kerbin-mining-corporation/Waterfall#37]
Dear Devs,

Firstly, mad props to your efforts. These new effects look lovely! However, not everybody is a VFX wizard like you lot and won't use the editor, instead opting for the prebuilt stuff. Could we get an option to hide the button (at least from inflight and inmap?) to clean up our toolbar?

If not directly, perhaps through the lovely [Toolbar Controller](https://forum.kerbalspaceprogram.com/index.php?/topic/169509-19x-toolbar-controller-for-modders/) mod?

**Comment by tyrope** [comment]
Turns out I'm a typical user who doesn't RTFM; it's a config file for those googling.

**Comment by LouisB3** [comment]
I've noticed that the settings file gets replaced every time CKAN updates Waterfall. To avoid having to re-disable the button every time that happens, I use a MM patch instead of editing the settings file directly:

```
@WATERFALL_SETTINGS:NEEDS[Waterfall]
{
  @ShowEffectEditor = false
}
```
