### ISSUE TITLE
Strange Yellow Plume

### ISSUE THREAD

**Issue by FifkoAstronom** [post-kerbin-mining-corporation/Waterfall#46]
I am using waterfall and on every single engine there is this yellow line of plume. I cant find it in the editor thought, so I
![WaterfallPlumeError](https://user-images.githubusercontent.com/76425755/109718876-21fec900-7ba8-11eb-8444-cbd119ac9108.png)
 think its bug or im doing something wrong. Please help.

**Comment by ChrisAdderley** [comment]
Can't repro.
