### ISSUE TITLE
Feature: allow controller slider to adapt to the min/max of the effect it is controlling

### ISSUE THREAD

**Issue by KnightofStJohn** [post-kerbin-mining-corporation/Waterfall#53]
• The slider that displays the modifier value goes out of visual range of the slider bar (on the left) if you have negative values for a random controller.

• The slider that displays the modifier value goes out of visual range of the slider bar (on the right) for the atmospheric controller. It starts out at a value of 1.07 at the runway, but the slider bar only goes to 1. (this has been happening since you added the exponential height compensation curve)

**Comment by ChrisAdderley** [comment]
I'm not super bothered by this one.

**Comment by KnightofStJohn** [comment]
me neither. just wrote this up so you have it. better than posting it in discord chat

**Comment by ChrisAdderley** [comment]
Actually done recently.
