### ISSUE TITLE
Feature: Controller for integration with other mods

### ISSUE THREAD

**Issue by ArXen42** [post-kerbin-mining-corporation/Waterfall#72]
### Problem

My use case: integration with Advanced Jet Engines (part of RO) that adds variable nozzle animation to some jet engines, making it necessary to scale effect to match visual model changes.
For demonstration, video of my recent attempt at making it play nice with Waterfall: https://youtu.be/5JuvO11Lg_A

In this particular example, effect is rescaled based on value from method `GetNozzleArea()` on subclassed `ModuleEngines`. This value is derived from complex jet engine simulation, so it cannot be easily substituted by `mach` or `throttle` controllers.

### Proposal

Add a new controller type that will have following parameters:

1. `methodOrPropertyName` - method or property to search on `ModuleEngines` using reflection. Should return numeric value, of course. For AJE integration that would be "GetNozzleArea()" method, for other mods something else.
1. _Maybe_ `moduleName` for additional flexibility in case desired value is not in the `ModuleEngines`, but not sure about that.
1. `minValue`/`maxValue`: expected value range. Values outside of that range will be clamped, values inside will be normalized to 0..1 range.
1. `responseRateUp`/`responseRateDown` - same as on `throttle` controller.

Example configuration:
```
CONTROLLER
{
  name                 = jetNozzleArea
  linkedTo             = custom_value
  methodOrPropertyName = GetNozzleArea
  engineID             = none
  minValue             = 0.4
  maxValue             = 1.25
  responseRateUp       = 1
  responseRateDown     = 1
}
```

### Motivation

To add easy config-only way of binding Waterfall effects to arbitrary values, leaving `custom` controller only for most complex cases.

I already made basic implementation for testing, so if you're ok with that idea, I will finish it and make PR when ready.
If it is "hard no", then no problem, I will go with `custom` controller and drive it from AJE.
I just felt that Waterfall could use some starting ground that would not require mod code changes from plume configs writer.

**Comment by ChrisAdderley** [comment]
I thought about this for ages but I think I prefer the current approach. However, if you want to implement, test and PR it, there's no reason why both approaches can't exist together.
