### ISSUE TITLE
Scatterer (v.0.770) and (probably) Waterfall shaders bad interaction

### ISSUE THREAD

**Issue by Araym-KSP** [post-kerbin-mining-corporation/Waterfall#73]
As posted also in the official forum:
https://forum.kerbalspaceprogram.com/index.php?/topic/196309-111x-waterfall-a-framework-for-continuous-mesh-driven-engine-effects-march-26/&do=findComment&comment=3980192

**Comment by Araym-KSP** [comment]
Some other thoughts about it, happening in the Scatterer thread, if it could eventually help to figure out the problem:
- https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip19x-110x-111x-scatterer-atmospheric-scattering-00770-17052021/&do=findComment&comment=3980660

- https://forum.kerbalspaceprogram.com/index.php?/topic/103963-wip19x-110x-111x-scatterer-atmospheric-scattering-00770-17052021/&do=findComment&comment=3980701

and related discussion.

**Comment by ChrisAdderley** [comment]
Doesnt seem to be an issue anymore.
