### ISSUE TITLE
Issue with copying to clipboard

### ISSUE THREAD

**Issue by FittedOrphan68** [post-kerbin-mining-corporation/Waterfall#82]
I've recently made some new plumes for RSS/RO using the in-game editor, copied the modules to my clipboard, made patches, etc. and have noticed errors popping up when using the parts after restarting. I didn't save the log(s) as I believe I've tracked down the issue. It's solved on my end at least... the copied output supplies:

MODULE {
name = ModuleWaterfallFX
.....
EFFECT {
......
MODEL {
.....
MATERIAL {
.....
FLOATMODIFIER {
name = aTintFallof          <----
.....
floatName = _TintFallof          <----
.....
}
FLOATMODIFIER {
name = aFallof          <----        
.....
floatName = _Fallof          <----
.....
}  }  }  }  }

I don't remember the exact verbiage of the error, but it was referencing the fact that there is no floatName "x." For whatever reason it seems to be outputting incorrect names. I hope you can still make sense of this chopped down version of the issue, but if not let me know and I'll recreate it to get a log for you. As usual, thanks for all you do. Cheers.

**Comment by ChrisAdderley** [comment]
Currently can't reproduce this.

**Comment by FittedOrphan68** [comment]
Likely a conflict of mods.
